//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfVista.Url {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UrlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrlResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfVista.Url.UrlResource", typeof(UrlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beneficiary/.
        /// </summary>
        internal static string ActualizarBeneficiario {
            get {
                return ResourceManager.GetString("ActualizarBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a employee/.
        /// </summary>
        internal static string ActualizarEmpleado {
            get {
                return ResourceManager.GetString("ActualizarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost:5197/api/.
        /// </summary>
        internal static string ApiBaseAddress {
            get {
                return ResourceManager.GetString("ApiBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beneficiary/.
        /// </summary>
        internal static string BorrarBeneficiario {
            get {
                return ResourceManager.GetString("BorrarBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a employee/.
        /// </summary>
        internal static string BorrarEmpleado {
            get {
                return ResourceManager.GetString("BorrarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beneficiary/.
        /// </summary>
        internal static string CrearBeneficiario {
            get {
                return ResourceManager.GetString("CrearBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a employee/.
        /// </summary>
        internal static string CrearEmpleado {
            get {
                return ResourceManager.GetString("CrearEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beneficiary/.
        /// </summary>
        internal static string ListaBeneficiarios {
            get {
                return ResourceManager.GetString("ListaBeneficiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a employee/.
        /// </summary>
        internal static string ListaEmpleados {
            get {
                return ResourceManager.GetString("ListaEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a login/.
        /// </summary>
        internal static string LoginController {
            get {
                return ResourceManager.GetString("LoginController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beneficiary/percentage/.
        /// </summary>
        internal static string PorcentajeParticipacionBeneficiario {
            get {
                return ResourceManager.GetString("PorcentajeParticipacionBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30.
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
    }
}
